export const mockUsers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Super Admin",
    joinedDate: "2023-01-15",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    role: "Master Admin",
    joinedDate: "2023-02-20",
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    role: "Unit Admin",
    joinedDate: "2023-03-10",
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana.prince@example.com",
    role: "Member",
    joinedDate: "2023-04-05",
  },
  {
    id: 5,
    name: "Evan Davis",
    email: "evan.davis@example.com",
    role: "Super Admin",
    joinedDate: "2023-05-22",
  },
  {
    id: 6,
    name: "Fiona Green",
    email: "fiona.green@example.com",
    role: "Master Admin",
    joinedDate: "2023-06-10",
  },
  {
    id: 7,
    name: "George White",
    email: "george.white@example.com",
    role: "Unit Admin",
    joinedDate: "2023-07-01",
  },
  {
    id: 8,
    name: "Hannah Black",
    email: "hannah.black@example.com",
    role: "Member",
    joinedDate: "2023-08-15",
  },
  {
    id: 9,
    name: "Ian Gray",
    email: "ian.gray@example.com",
    role: "Super Admin",
    joinedDate: "2023-09-25",
  },
  {
    id: 10,
    name: "Jessica Blue",
    email: "jessica.blue@example.com",
    role: "Master Admin",
    joinedDate: "2023-10-30",
  },
  {
    id: 11,
    name: "Kevin Brown",
    email: "kevin.brown@example.com",
    role: "Unit Admin",
    joinedDate: "2023-11-05",
  },
  {
    id: 12,
    name: "Laura White",
    email: "laura.white@example.com",
    role: "Member",
    joinedDate: "2023-12-12",
  },
  {
    id: 13,
    name: "Mike Green",
    email: "mike.green@example.com",
    role: "Super Admin",
    joinedDate: "2024-01-20",
  },
  {
    id: 14,
    name: "Nina Black",
    email: "nina.black@example.com",
    role: "Master Admin",
    joinedDate: "2024-02-14",
  },
  {
    id: 15,
    name: "Oscar Brown",
    email: "oscar.brown@example.com",
    role: "Unit Admin",
    joinedDate: "2024-03-18",
  },
  {
    id: 16,
    name: "Paul White",
    email: "paul.white@example.com",
    role: "Member",
    joinedDate: "2024-04-25",
  },
  {
    id: 17,
    name: "Quincy Green",
    email: "quincy.green@example.com",
    role: "Super Admin",
    joinedDate: "2024-05-30",
  },
  {
    id: 18,
    name: "Rachel Black",
    email: "rachel.black@example.com",
    role: "Master Admin",
    joinedDate: "2024-06-15",
  },
  {
    id: 19,
    name: "Sam Brown",
    email: "sam.brown@example.com",
    role: "Unit Admin",
    joinedDate: "2024-07-01",
  },
  {
    id: 20,
    name: "Tina White",
    email: "tina.white@example.com",
    role: "Member",
    joinedDate: "2024-08-10",
  },
];
